// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQiyBffFLS-ntdsQOHzQaqoTz7GySOSto',
    appId: '1:45302213570:web:911453efc395d33d27c45b',
    messagingSenderId: '45302213570',
    projectId: 'campass-1cc27',
    authDomain: 'campass-1cc27.firebaseapp.com',
    storageBucket: 'campass-1cc27.firebasestorage.app',
    measurementId: 'G-ZE7GCXHGLN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtxGnkMHpfcst-IBQWn2HCo1wfZkO6S8Y',
    appId: '1:45302213570:android:e3a1acb8fccf8f7527c45b',
    messagingSenderId: '45302213570',
    projectId: 'campass-1cc27',
    storageBucket: 'campass-1cc27.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlyVta6c6C1J0O2RKvsx3n_Dzz9bR5Phk',
    appId: '1:45302213570:ios:11e17c880c53e5ea27c45b',
    messagingSenderId: '45302213570',
    projectId: 'campass-1cc27',
    storageBucket: 'campass-1cc27.firebasestorage.app',
    iosBundleId: 'com.example.campassApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlyVta6c6C1J0O2RKvsx3n_Dzz9bR5Phk',
    appId: '1:45302213570:ios:11e17c880c53e5ea27c45b',
    messagingSenderId: '45302213570',
    projectId: 'campass-1cc27',
    storageBucket: 'campass-1cc27.firebasestorage.app',
    iosBundleId: 'com.example.campassApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQiyBffFLS-ntdsQOHzQaqoTz7GySOSto',
    appId: '1:45302213570:web:cbd78a3dfe20225c27c45b',
    messagingSenderId: '45302213570',
    projectId: 'campass-1cc27',
    authDomain: 'campass-1cc27.firebaseapp.com',
    storageBucket: 'campass-1cc27.firebasestorage.app',
    measurementId: 'G-E2DRZP9L8S',
  );

}